package com.etc.entity;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cname
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.mobile
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.status
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cid
     *
     * @return the value of customer.cid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cid
     *
     * @param cid the value for customer.cid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cname
     *
     * @return the value of customer.cname
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cname
     *
     * @param cname the value for customer.cname
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.mobile
     *
     * @return the value of customer.mobile
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.mobile
     *
     * @param mobile the value for customer.mobile
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.status
     *
     * @return the value of customer.status
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.status
     *
     * @param status the value for customer.status
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Customer(Integer cid, String cname, String mobile, Integer status) {
		this.cid = cid;
		this.cname = cname;
		this.mobile = mobile;
		this.status = status;
	}

	public Customer() {
	}
	
	
    
    
}