package com.etc.entity;

public class Detail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.did
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.oid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.gid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.count
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.amount
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    private Double amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.did
     *
     * @return the value of detail.did
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.did
     *
     * @param did the value for detail.did
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.oid
     *
     * @return the value of detail.oid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.oid
     *
     * @param oid the value for detail.oid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.gid
     *
     * @return the value of detail.gid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.gid
     *
     * @param gid the value for detail.gid
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.count
     *
     * @return the value of detail.count
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.count
     *
     * @param count the value for detail.count
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.amount
     *
     * @return the value of detail.amount
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.amount
     *
     * @param amount the value for detail.amount
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }
}