package com.etc.entity;

public class Orderinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.oid
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.orderNO
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.total
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.cid
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.status
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.oid
     *
     * @return the value of orderinfo.oid
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.oid
     *
     * @param oid the value for orderinfo.oid
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.orderNO
     *
     * @return the value of orderinfo.orderNO
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.orderNO
     *
     * @param orderno the value for orderinfo.orderNO
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.total
     *
     * @return the value of orderinfo.total
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.total
     *
     * @param total the value for orderinfo.total
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.cid
     *
     * @return the value of orderinfo.cid
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.cid
     *
     * @param cid the value for orderinfo.cid
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.status
     *
     * @return the value of orderinfo.status
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.status
     *
     * @param status the value for orderinfo.status
     *
     * @mbggenerated Wed May 23 14:45:02 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}