package com.etc.dao;

import com.etc.entity.Detail;
import com.etc.entity.DetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int countByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int deleteByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int insertSelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    List<Detail> selectByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    Detail selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Detail record, @Param("example") DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int updateByExample(@Param("record") Detail record, @Param("example") DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int updateByPrimaryKeySelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Wed May 23 08:46:34 CST 2018
     */
    int updateByPrimaryKey(Detail record);
}